// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// IoK8sApimachineryPkgApisMetaV1Time io k8s apimachinery pkg apis meta v1 time
// swagger:model io.k8s.apimachinery.pkg.apis.meta.v1.Time
type IoK8sApimachineryPkgApisMetaV1Time strfmt.DateTime

// Validate validates this io k8s apimachinery pkg apis meta v1 time
func (m IoK8sApimachineryPkgApisMetaV1Time) Validate(formats strfmt.Registry) error {
	return nil
}
