// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IoK8sApimachineryPkgApisMetaV1ObjectMetaOwnerReferences List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
// swagger:model ioK8sApimachineryPkgApisMetaV1ObjectMetaOwnerReferences
type IoK8sApimachineryPkgApisMetaV1ObjectMetaOwnerReferences []*IoK8sApimachineryPkgApisMetaV1OwnerReference

// Validate validates this io k8s apimachinery pkg apis meta v1 object meta owner references
func (m IoK8sApimachineryPkgApisMetaV1ObjectMetaOwnerReferences) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
