// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IoK8sApimachineryPkgApisMetaV1StatusDetailsCauses The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.
// swagger:model ioK8sApimachineryPkgApisMetaV1StatusDetailsCauses
type IoK8sApimachineryPkgApisMetaV1StatusDetailsCauses []*IoK8sApimachineryPkgApisMetaV1StatusCause

// Validate validates this io k8s apimachinery pkg apis meta v1 status details causes
func (m IoK8sApimachineryPkgApisMetaV1StatusDetailsCauses) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
