// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo AuthInfo holds public information that describes how a client can get credentials to access the cluster. For example, OAuth2 client registration endpoints and supported flows, or Kerberos servers locations.
//
// It should not hold any private or sensitive information.
// swagger:model io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthInfo
type IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo struct {

	// providers
	Providers IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfoProviders `json:"providers"`
}

// Validate validates this io k8s cluster registry pkg apis clusterregistry v1alpha1 auth info
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo) UnmarshalBinary(b []byte) error {
	var res IoK8sClusterRegistryPkgApisClusterregistryV1alpha1AuthInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
