// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sApimachineryPkgApisMetaV1Initializer Initializer is information about an initializer that has not yet completed.
// swagger:model io.k8s.apimachinery.pkg.apis.meta.v1.Initializer
type IoK8sApimachineryPkgApisMetaV1Initializer struct {

	// name of the process that is responsible for initializing this object.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this io k8s apimachinery pkg apis meta v1 initializer
func (m *IoK8sApimachineryPkgApisMetaV1Initializer) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sApimachineryPkgApisMetaV1Initializer) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sApimachineryPkgApisMetaV1Initializer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sApimachineryPkgApisMetaV1Initializer) UnmarshalBinary(b []byte) error {
	var res IoK8sApimachineryPkgApisMetaV1Initializer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
