// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR ServerAddressByClientCIDR helps clients determine the server address that they should use, depending on the ClientCIDR that they match.
// swagger:model io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ServerAddressByClientCIDR
type IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR struct {

	// The CIDR with which clients can match their IP to figure out if they should use the corresponding server address.
	ClientCIDR string `json:"clientCIDR,omitempty"`

	// Address of this server, suitable for a client that matches the above CIDR. This can be a hostname, hostname:port, IP or IP:port.
	ServerAddress string `json:"serverAddress,omitempty"`
}

// Validate validates this io k8s cluster registry pkg apis clusterregistry v1alpha1 server address by client c ID r
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR) UnmarshalBinary(b []byte) error {
	var res IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
