// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IoK8sClusterRegistryPkgApisClusterregistryV1alpha1KubernetesAPIEndpointsServerEndpoints ServerEndpoints specifies the address(es) of the Kubernetes API server’s network identity or identities.
// swagger:model ioK8sClusterRegistryPkgApisClusterregistryV1alpha1KubernetesApiEndpointsServerEndpoints
type IoK8sClusterRegistryPkgApisClusterregistryV1alpha1KubernetesAPIEndpointsServerEndpoints []*IoK8sClusterRegistryPkgApisClusterregistryV1alpha1ServerAddressByClientCIDR

// Validate validates this io k8s cluster registry pkg apis clusterregistry v1alpha1 kubernetes Api endpoints server endpoints
func (m IoK8sClusterRegistryPkgApisClusterregistryV1alpha1KubernetesAPIEndpointsServerEndpoints) Validate(formats strfmt.Registry) error {
	var res []error

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
