// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ReleaseMetadataAnnotations release metadata annotations
// swagger:model releaseMetadataAnnotations
type ReleaseMetadataAnnotations struct {

	// key
	Key string `json:"Key,omitempty"`

	// value
	Value string `json:"Value,omitempty"`
}

// Validate validates this release metadata annotations
func (m *ReleaseMetadataAnnotations) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseMetadataAnnotations) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseMetadataAnnotations) UnmarshalBinary(b []byte) error {
	var res ReleaseMetadataAnnotations
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
