// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ReleaseMaintainer release maintainer
// swagger:model release.Maintainer
type ReleaseMaintainer struct {

	// email
	Email string `json:"Email,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// Url
	URL string `json:"Url,omitempty"`
}

// Validate validates this release maintainer
func (m *ReleaseMaintainer) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseMaintainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseMaintainer) UnmarshalBinary(b []byte) error {
	var res ReleaseMaintainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
