// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Optikon
Optikon is an edge computing API for Kubernetes. It exposes Helm and the cluster registry for a comprehensive UI


    Schemes:
      http
      https
    Host: localhost
    BasePath: /v0
    Version: 0.0.1
    Contact: <stelouie@cisco.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
