// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Optikon is an edge computing API for Kubernetes. It exposes Helm and the cluster registry for a comprehensive UI",
    "title": "Optikon",
    "contact": {
      "email": "stelouie@cisco.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/v0",
  "paths": {
    "/clusters": {
      "get": {
        "description": "Returns a list of clusters",
        "produces": [
          "application/json"
        ],
        "tags": [
          "clusters"
        ],
        "summary": "Returns all clusters",
        "operationId": "getClusters",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.Cluster"
              }
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clusters"
        ],
        "summary": "Add a new cluster to optikon",
        "operationId": "addCluster",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.Cluster"
            }
          }
        ],
        "responses": {
          "201": {
            "$ref": "#/responses/Created"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/clusters/{clusterId}": {
      "get": {
        "description": "Returns a single cluster",
        "produces": [
          "application/json"
        ],
        "tags": [
          "clusters"
        ],
        "summary": "Find cluster by ID",
        "operationId": "getClusterById",
        "parameters": [
          {
            "type": "string",
            "description": "ID of cluster to return",
            "name": "clusterId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.Cluster"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "clusters"
        ],
        "summary": "Update an existing cluster",
        "operationId": "updateCluster",
        "parameters": [
          {
            "type": "string",
            "description": "Cluster id to update",
            "name": "clusterId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.Cluster"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "clusters"
        ],
        "summary": "Deletes a cluster",
        "operationId": "deleteCluster",
        "parameters": [
          {
            "type": "string",
            "description": "Cluster id to delete",
            "name": "clusterId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/releases": {
      "get": {
        "description": "Returns a list of releases",
        "produces": [
          "application/json"
        ],
        "tags": [
          "releases"
        ],
        "summary": "Returns all releases",
        "operationId": "getReleases",
        "parameters": [
          {
            "type": "string",
            "description": "The node labels to identify applicable clusters",
            "name": "labels",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/release.Release"
              }
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "releases"
        ],
        "summary": "Add a new release to the clusters",
        "operationId": "addReleases",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload",
            "name": "chartTar",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the helm release",
            "name": "name",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The kubernetes namespace to be used",
            "name": "namespace",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The node labels to identify applicable clusters",
            "name": "labels",
            "in": "query"
          }
        ],
        "responses": {
          "201": {
            "$ref": "#/responses/Created"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    },
    "/releases/{releaseId}": {
      "get": {
        "description": "Returns a single release",
        "produces": [
          "application/json"
        ],
        "tags": [
          "releases"
        ],
        "summary": "Find release by ID",
        "operationId": "getReleaseById",
        "parameters": [
          {
            "type": "string",
            "description": "ID of release to return",
            "name": "releaseId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The node labels to identify applicable clusters",
            "name": "labels",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/release.Release"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "put": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "releases"
        ],
        "summary": "Update an existing release",
        "operationId": "updateRelease",
        "parameters": [
          {
            "type": "string",
            "description": "ID of release to update",
            "name": "releaseId",
            "in": "path",
            "required": true
          },
          {
            "type": "file",
            "description": "The file to upload",
            "name": "chartTar",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The node labels to identify applicable clusters",
            "name": "labels",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "releases"
        ],
        "summary": "Delete release by ID",
        "operationId": "deleteRelease",
        "parameters": [
          {
            "type": "string",
            "description": "ID of release to return",
            "name": "releaseId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The node labels to identify applicable clusters",
            "name": "labels",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "500": {
            "$ref": "#/responses/InternalServerError"
          }
        }
      }
    }
  },
  "definitions": {
    "APIResponse": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "chart.Chart": {
      "type": "object",
      "properties": {
        "Config": {
          "$ref": "#/definitions/chart.Config"
        },
        "Dependencies": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chart.Chart"
          }
        },
        "Files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/protobuf.Any"
          }
        },
        "Metadata": {
          "$ref": "#/definitions/chart.Metadata"
        },
        "Template": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chart.Template"
          }
        }
      }
    },
    "chart.Config": {
      "type": "object",
      "properties": {
        "Raw": {
          "type": "string"
        },
        "Values": {
          "$ref": "#/definitions/chart.Map"
        }
      }
    },
    "chart.Maintainer": {
      "type": "object",
      "properties": {
        "Email": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Url": {
          "type": "string"
        }
      }
    },
    "chart.Map": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/chart.Value"
      }
    },
    "chart.Metadata": {
      "type": "object",
      "properties": {
        "Annotations": {
          "$ref": "#/definitions/chart.Map"
        },
        "ApiVersion": {
          "type": "string"
        },
        "AppVersion": {
          "type": "string"
        },
        "Condition": {
          "type": "string"
        },
        "Deprecated": {
          "type": "boolean"
        },
        "Description": {
          "type": "string"
        },
        "Engine": {
          "type": "string",
          "enum": [
            "UNKNOWN",
            "GOTPL"
          ]
        },
        "Home": {
          "type": "string"
        },
        "Icon": {
          "type": "string"
        },
        "Keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "KubeVersion": {
          "type": "string"
        },
        "Maintainers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/chart.Maintainer"
          }
        },
        "Name": {
          "type": "string"
        },
        "Sources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Tags": {
          "type": "string"
        },
        "TillerVersion": {
          "type": "string"
        },
        "Version": {
          "type": "string"
        }
      }
    },
    "chart.Template": {
      "type": "object",
      "properties": {
        "Data": {
          "type": "string",
          "format": "byte"
        },
        "Name": {
          "type": "string"
        }
      }
    },
    "chart.Value": {
      "type": "object",
      "properties": {
        "Key": {
          "type": "string"
        },
        "Value": {
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.Initializer": {
      "description": "Initializer is information about an initializer that has not yet completed.",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "description": "name of the process that is responsible for initializing this object.",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.Initializers": {
      "description": "Initializers tracks the progress of initialization.",
      "required": [
        "pending"
      ],
      "properties": {
        "pending": {
          "description": "Pending is a list of initializers that must execute in order before this object is visible. When the last pending initializer is removed, and no failing result is set, the initializers struct will be set to nil and the object is considered as initialized and visible to all clients.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Initializer"
          },
          "x-kubernetes-patch-merge-key": "name",
          "x-kubernetes-patch-strategy": "merge"
        },
        "result": {
          "description": "If result is set with the Failure field, the object will be persisted to storage and then deleted, ensuring that other clients can observe the deletion.",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Status"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta": {
      "description": "ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.",
      "properties": {
        "continue": {
          "description": "continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response.",
          "type": "string"
        },
        "resourceVersion": {
          "description": "String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency",
          "type": "string"
        },
        "selfLink": {
          "description": "selfLink is a URL representing this object. Populated by the system. Read-only.",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta": {
      "description": "ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.",
      "properties": {
        "annotations": {
          "description": "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "clusterName": {
          "description": "The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request.",
          "type": "string"
        },
        "creationTimestamp": {
          "description": "CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.\n\nPopulated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        },
        "deletionGracePeriodSeconds": {
          "description": "Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.",
          "type": "integer",
          "format": "int64"
        },
        "deletionTimestamp": {
          "description": "DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field. Once set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.\n\nPopulated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
        },
        "finalizers": {
          "description": "Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed.",
          "type": "array",
          "items": {
            "type": "string"
          },
          "x-kubernetes-patch-strategy": "merge"
        },
        "generateName": {
          "description": "GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\n\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\n\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#idempotency",
          "type": "string"
        },
        "generation": {
          "description": "A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.",
          "type": "integer",
          "format": "int64"
        },
        "initializers": {
          "description": "An initializer is a controller which enforces some system invariant at object creation time. This field is a list of initializers that have not yet acted on this object. If nil or empty, this object has been completely initialized. Otherwise, the object is considered uninitialized and is hidden (in list/watch and get calls) from clients that haven't explicitly asked to observe uninitialized objects.\n\nWhen an object is created, the system will populate this list with the current set of initializers. Only privileged users may set or modify this list. Once it is empty, it may not be modified further by any user.",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Initializers"
        },
        "labels": {
          "description": "Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "name": {
          "description": "Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
          "type": "string"
        },
        "namespace": {
          "description": "Namespace defines the space within each name must be unique. An empty namespace is equivalent to the \"default\" namespace, but \"default\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\n\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces",
          "type": "string"
        },
        "ownerReferences": {
          "description": "List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference"
          },
          "x-kubernetes-patch-merge-key": "uid",
          "x-kubernetes-patch-strategy": "merge"
        },
        "resourceVersion": {
          "description": "An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\n\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#concurrency-control-and-consistency",
          "type": "string"
        },
        "selfLink": {
          "description": "SelfLink is a URL representing this object. Populated by the system. Read-only.",
          "type": "string"
        },
        "uid": {
          "description": "UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\n\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.OwnerReference": {
      "description": "OwnerReference contains enough information to let you identify an owning object. Currently, an owning object must be in the same namespace, so there is no namespace field.",
      "required": [
        "apiVersion",
        "kind",
        "name",
        "uid"
      ],
      "properties": {
        "apiVersion": {
          "description": "API version of the referent.",
          "type": "string"
        },
        "blockOwnerDeletion": {
          "description": "If true, AND if the owner has the \"foregroundDeletion\" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. Defaults to false. To set this field, a user needs \"delete\" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.",
          "type": "boolean"
        },
        "controller": {
          "description": "If true, this reference points to the managing controller.",
          "type": "boolean"
        },
        "kind": {
          "description": "Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
          "type": "string"
        },
        "name": {
          "description": "Name of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
          "type": "string"
        },
        "uid": {
          "description": "UID of the referent. More info: http://kubernetes.io/docs/user-guide/identifiers#uids",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.Status": {
      "description": "Status is a return value for calls that don't return other objects.",
      "properties": {
        "apiVersion": {
          "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
          "type": "string"
        },
        "code": {
          "description": "Suggested HTTP return code for this status, 0 if not set.",
          "type": "integer",
          "format": "int32"
        },
        "details": {
          "description": "Extended data associated with the reason.  Each reason may define its own extended details. This field is optional and the data returned is not guaranteed to conform to any schema except that defined by the reason type.",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.StatusDetails"
        },
        "kind": {
          "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
          "type": "string"
        },
        "message": {
          "description": "A human-readable description of the status of this operation.",
          "type": "string"
        },
        "metadata": {
          "description": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ListMeta"
        },
        "reason": {
          "description": "A machine-readable description of why this operation is in the \"Failure\" status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.",
          "type": "string"
        },
        "status": {
          "description": "Status of the operation. One of: \"Success\" or \"Failure\". More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#spec-and-status",
          "type": "string"
        }
      },
      "x-kubernetes-group-version-kind": [
        {
          "group": "",
          "kind": "Status",
          "version": "v1"
        }
      ]
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.StatusCause": {
      "description": "StatusCause provides more information about an api.Status failure, including cases when multiple errors are encountered.",
      "properties": {
        "field": {
          "description": "The field of the resource that has caused this error, as named by its JSON serialization. May include dot and postfix notation for nested attributes. Arrays are zero-indexed.  Fields may appear more than once in an array of causes due to fields having multiple errors. Optional.\n\nExamples:\n  \"name\" - the field \"name\" on the current resource\n  \"items[0].name\" - the field \"name\" on the first array entry in \"items\"",
          "type": "string"
        },
        "message": {
          "description": "A human-readable description of the cause of the error.  This field may be presented as-is to a reader.",
          "type": "string"
        },
        "reason": {
          "description": "A machine-readable description of the cause of the error. If this value is empty there is no information available.",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.StatusDetails": {
      "description": "StatusDetails is a set of additional properties that MAY be set by the server to provide additional information about a response. The Reason field of a Status object defines what attributes will be set. Clients must ignore fields that do not match the defined type of each attribute, and should assume that any attribute may be empty, invalid, or under defined.",
      "properties": {
        "causes": {
          "description": "The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.StatusCause"
          }
        },
        "group": {
          "description": "The group attribute of the resource associated with the status StatusReason.",
          "type": "string"
        },
        "kind": {
          "description": "The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
          "type": "string"
        },
        "name": {
          "description": "The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).",
          "type": "string"
        },
        "retryAfterSeconds": {
          "description": "If specified, the time in seconds before the operation should be retried. Some errors may indicate the client must take an alternate action - for those errors this field may indicate how long to wait before taking the alternate action.",
          "type": "integer",
          "format": "int32"
        },
        "uid": {
          "description": "UID of the resource. (when there is a single resource which can be described). More info: http://kubernetes.io/docs/user-guide/identifiers#uids",
          "type": "string"
        }
      }
    },
    "io.k8s.apimachinery.pkg.apis.meta.v1.Time": {
      "type": "string",
      "format": "date-time"
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthInfo": {
      "description": "AuthInfo holds public information that describes how a client can get credentials to access the cluster. For example, OAuth2 client registration endpoints and supported flows, or Kerberos servers locations.\n\nIt should not hold any private or sensitive information.",
      "properties": {
        "providers": {
          "description": "AuthProviders is a list of configurations for auth providers.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthProviderConfig"
          }
        }
      }
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthProviderConfig": {
      "description": "AuthProviderConfig contains the information necessary for a client to authenticate to a Kubernetes API server. It is modeled after k8s.io/client-go/tools/clientcmd/api/v1.AuthProviderConfig.",
      "properties": {
        "config": {
          "description": "Config is a map of values that contains the information necessary for a client to determine how to authenticate to a Kubernetes API server.",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "name": {
          "description": "Name is the name of this configuration.",
          "type": "string"
        },
        "type": {
          "description": "Type contains type information about this auth provider. Clients of the cluster registry should use this field to differentiate between different kinds of authentication providers.",
          "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthProviderType"
        }
      }
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthProviderType": {
      "description": "AuthProviderType contains metadata about the auth provider. It should be used by clients to differentiate between different kinds of auth providers, and to select a relevant provider for the client's configuration. For example, a controller would look for a provider type that denotes a service account that it should use to access the cluster, whereas a user would look for a provider type that denotes an authentication system from which they should request a token.",
      "properties": {
        "name": {
          "description": "Name is the name of the auth provider.",
          "type": "string"
        }
      }
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.Cluster": {
      "description": "Cluster contains information about a cluster in a cluster registry.",
      "properties": {
        "apiVersion": {
          "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
          "type": "string"
        },
        "kind": {
          "description": "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
          "type": "string"
        },
        "metadata": {
          "description": "Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata",
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta"
        },
        "spec": {
          "description": "Spec is the specification of the cluster. This may or may not be reconciled by an active controller.",
          "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ClusterSpec"
        },
        "status": {
          "description": "Status is the status of the cluster. It is optional, and can be left nil to imply that the cluster status is not being reported.",
          "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ClusterStatus"
        }
      },
      "x-kubernetes-group-version-kind": [
        {
          "group": "clusterregistry.k8s.io",
          "kind": "Cluster",
          "version": "v1alpha1"
        }
      ]
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ClusterSpec": {
      "description": "ClusterSpec contains the specification of a cluster.",
      "properties": {
        "authInfo": {
          "description": "AuthInfo contains public information that can be used to authenticate to and authorize with this cluster. It is not meant to store private information (e.g., tokens or client certificates) and cluster registry implementations are not expected to provide hardened storage for secrets.",
          "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.AuthInfo"
        },
        "kubernetesApiEndpoints": {
          "description": "KubernetesAPIEndpoints represents the endpoints of the API server for this cluster.",
          "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.KubernetesAPIEndpoints"
        }
      }
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ClusterStatus": {
      "description": "ClusterStatus contains the status of a cluster."
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.KubernetesAPIEndpoints": {
      "description": "KubernetesAPIEndpoints represents the endpoints for one and only one Kubernetes API server.",
      "properties": {
        "caBundle": {
          "description": "CABundle contains the certificate authority information.",
          "type": "string",
          "format": "byte"
        },
        "serverEndpoints": {
          "description": "ServerEndpoints specifies the address(es) of the Kubernetes API server’s network identity or identities.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ServerAddressByClientCIDR"
          }
        }
      }
    },
    "io.k8s.cluster-registry.pkg.apis.clusterregistry.v1alpha1.ServerAddressByClientCIDR": {
      "description": "ServerAddressByClientCIDR helps clients determine the server address that they should use, depending on the ClientCIDR that they match.",
      "properties": {
        "clientCIDR": {
          "description": "The CIDR with which clients can match their IP to figure out if they should use the corresponding server address.",
          "type": "string"
        },
        "serverAddress": {
          "description": "Address of this server, suitable for a client that matches the above CIDR. This can be a hostname, hostname:port, IP or IP:port.",
          "type": "string"
        }
      }
    },
    "protobuf.Any": {
      "type": "object",
      "properties": {
        "Type_Url": {
          "type": "string"
        },
        "Value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "release.Files": {
      "type": "object",
      "properties": {
        "Key": {
          "type": "string"
        },
        "Value": {
          "type": "string",
          "format": "byte"
        }
      }
    },
    "release.Hook": {
      "type": "object",
      "properties": {
        "DeletePolicies": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "SUCCEEDED",
              "FAILED",
              "BEFORE_HOOK_CREATION"
            ]
          }
        },
        "Events": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "UNKNOWN",
              "PRE_INSTALL",
              "POST_INSTALL",
              "PRE_DELETE",
              "POST_DELETE",
              "PRE_UPGRADE",
              "POST_UPGRADE",
              "PRE_ROLLBACK",
              "POST_ROLLBACK",
              "RELEASE_TEST_SUCCESS",
              "RELEASE_TEST_FAILURE"
            ]
          }
        },
        "Kind": {
          "type": "string"
        },
        "LastRun": {
          "type": "string"
        },
        "Manifest": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Path": {
          "type": "string"
        },
        "Weight": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "release.Info": {
      "type": "object",
      "properties": {
        "Deleted": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "FirstDeployed": {
          "type": "string"
        },
        "LastDeployed": {
          "type": "string"
        },
        "Status": {
          "$ref": "#/definitions/release.Status"
        }
      }
    },
    "release.Release": {
      "type": "object",
      "properties": {
        "Chart": {
          "$ref": "#/definitions/chart.Chart"
        },
        "Config": {
          "$ref": "#/definitions/chart.Config"
        },
        "Hooks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/release.Hook"
          }
        },
        "Info": {
          "$ref": "#/definitions/release.Info"
        },
        "Manifest": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "Namespace": {
          "type": "string"
        },
        "OnCluster": {
          "type": "string"
        },
        "Version": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "release.Status": {
      "type": "object",
      "properties": {
        "Code": {
          "type": "string",
          "enum": [
            "UNKNOWN",
            "DEPLOYED",
            "DELETED",
            "SUSPENDED",
            "FAILED",
            "DELETING",
            "PENDING_INSTALL",
            "PENDING_UPGRADE",
            "PENDING_ROLLBACK"
          ]
        },
        "LastTestSuiteRun": {
          "$ref": "#/definitions/release.TestSuite"
        },
        "Notes": {
          "type": "string"
        },
        "Resources": {
          "type": "string"
        }
      }
    },
    "release.TestRun": {
      "type": "object",
      "properties": {
        "CompletedAt": {
          "type": "string"
        },
        "Info": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        },
        "StartedAt": {
          "type": "string"
        },
        "Status": {
          "type": "string"
        }
      }
    },
    "release.TestSuite": {
      "type": "object",
      "properties": {
        "CompletedAt": {
          "type": "string"
        },
        "Results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/release.TestRun"
          }
        },
        "StartedAt": {
          "type": "string"
        }
      }
    }
  },
  "responses": {
    "BadRequest": {
      "description": "Bad Request",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    },
    "Created": {
      "description": "Created",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    },
    "InternalServerError": {
      "description": "Internal Server Error",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    },
    "NotFound": {
      "description": "The specified resource was not found",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    },
    "ServiceUnavailable": {
      "description": "Service Unavailable",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/APIResponse"
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your clusters",
      "name": "clusters",
      "externalDocs": {
        "description": "Cluster Registry v0.0.3",
        "url": "https://github.com/kubernetes/cluster-registry/tree/v0.0.3"
      }
    },
    {
      "description": "Access to all helm releases",
      "name": "releases",
      "externalDocs": {
        "description": "Helm v2.8.2",
        "url": "https://github.com/kubernetes/helm/tree/v2.8.2"
      }
    }
  ]
}`))
}
