// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	flag "github.com/spf13/pflag"

	"wwwin-github.cisco.com/edge/optikon-api/api/v0/server/restapi"
	"wwwin-github.cisco.com/edge/optikon-api/api/v0/server/restapi/operations"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
	if err != nil {
		log.Fatalln(err)
	}
	var server *restapi.Server // make sure init is called

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  optikon-server [OPTIONS]\n\n")

		title := "Optikon"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "Optikon is an edge computing API for Kubernetes. It exposes Helm and the cluster registry for a comprehensive UI"
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}
	// parse the CLI flags
	flag.Parse()
	api := operations.NewOptikonAPI(swaggerSpec)

	// get server with flag values filled out
	server = restapi.NewServer(api)
	server.ConfigureAPI()
	server.ConfigureFlags()
	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
}
