// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// AddReleasesCreatedCode is the HTTP code returned for type AddReleasesCreated
const AddReleasesCreatedCode int = 201

/*AddReleasesCreated Created

swagger:response addReleasesCreated
*/
type AddReleasesCreated struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddReleasesCreated creates AddReleasesCreated with default headers values
func NewAddReleasesCreated() *AddReleasesCreated {
	return &AddReleasesCreated{}
}

// WithPayload adds the payload to the add releases created response
func (o *AddReleasesCreated) WithPayload(payload *models.APIResponse) *AddReleasesCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add releases created response
func (o *AddReleasesCreated) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddReleasesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddReleasesBadRequestCode is the HTTP code returned for type AddReleasesBadRequest
const AddReleasesBadRequestCode int = 400

/*AddReleasesBadRequest Bad Request

swagger:response addReleasesBadRequest
*/
type AddReleasesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddReleasesBadRequest creates AddReleasesBadRequest with default headers values
func NewAddReleasesBadRequest() *AddReleasesBadRequest {
	return &AddReleasesBadRequest{}
}

// WithPayload adds the payload to the add releases bad request response
func (o *AddReleasesBadRequest) WithPayload(payload *models.APIResponse) *AddReleasesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add releases bad request response
func (o *AddReleasesBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddReleasesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddReleasesUnauthorizedCode is the HTTP code returned for type AddReleasesUnauthorized
const AddReleasesUnauthorizedCode int = 401

/*AddReleasesUnauthorized Unauthorized

swagger:response addReleasesUnauthorized
*/
type AddReleasesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddReleasesUnauthorized creates AddReleasesUnauthorized with default headers values
func NewAddReleasesUnauthorized() *AddReleasesUnauthorized {
	return &AddReleasesUnauthorized{}
}

// WithPayload adds the payload to the add releases unauthorized response
func (o *AddReleasesUnauthorized) WithPayload(payload *models.APIResponse) *AddReleasesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add releases unauthorized response
func (o *AddReleasesUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddReleasesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddReleasesInternalServerErrorCode is the HTTP code returned for type AddReleasesInternalServerError
const AddReleasesInternalServerErrorCode int = 500

/*AddReleasesInternalServerError Internal Server Error

swagger:response addReleasesInternalServerError
*/
type AddReleasesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddReleasesInternalServerError creates AddReleasesInternalServerError with default headers values
func NewAddReleasesInternalServerError() *AddReleasesInternalServerError {
	return &AddReleasesInternalServerError{}
}

// WithPayload adds the payload to the add releases internal server error response
func (o *AddReleasesInternalServerError) WithPayload(payload *models.APIResponse) *AddReleasesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add releases internal server error response
func (o *AddReleasesInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddReleasesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
