// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/optikon/api/api/v0/models"
)

// DeleteReleaseOKCode is the HTTP code returned for type DeleteReleaseOK
const DeleteReleaseOKCode int = 200

/*DeleteReleaseOK OK

swagger:response deleteReleaseOK
*/
type DeleteReleaseOK struct {
}

// NewDeleteReleaseOK creates DeleteReleaseOK with default headers values
func NewDeleteReleaseOK() *DeleteReleaseOK {
	return &DeleteReleaseOK{}
}

// WriteResponse to the client
func (o *DeleteReleaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteReleaseBadRequestCode is the HTTP code returned for type DeleteReleaseBadRequest
const DeleteReleaseBadRequestCode int = 400

/*DeleteReleaseBadRequest Bad Request

swagger:response deleteReleaseBadRequest
*/
type DeleteReleaseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteReleaseBadRequest creates DeleteReleaseBadRequest with default headers values
func NewDeleteReleaseBadRequest() *DeleteReleaseBadRequest {
	return &DeleteReleaseBadRequest{}
}

// WithPayload adds the payload to the delete release bad request response
func (o *DeleteReleaseBadRequest) WithPayload(payload *models.APIResponse) *DeleteReleaseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release bad request response
func (o *DeleteReleaseBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteReleaseUnauthorizedCode is the HTTP code returned for type DeleteReleaseUnauthorized
const DeleteReleaseUnauthorizedCode int = 401

/*DeleteReleaseUnauthorized Unauthorized

swagger:response deleteReleaseUnauthorized
*/
type DeleteReleaseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteReleaseUnauthorized creates DeleteReleaseUnauthorized with default headers values
func NewDeleteReleaseUnauthorized() *DeleteReleaseUnauthorized {
	return &DeleteReleaseUnauthorized{}
}

// WithPayload adds the payload to the delete release unauthorized response
func (o *DeleteReleaseUnauthorized) WithPayload(payload *models.APIResponse) *DeleteReleaseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release unauthorized response
func (o *DeleteReleaseUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteReleaseNotFoundCode is the HTTP code returned for type DeleteReleaseNotFound
const DeleteReleaseNotFoundCode int = 404

/*DeleteReleaseNotFound The specified resource was not found

swagger:response deleteReleaseNotFound
*/
type DeleteReleaseNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteReleaseNotFound creates DeleteReleaseNotFound with default headers values
func NewDeleteReleaseNotFound() *DeleteReleaseNotFound {
	return &DeleteReleaseNotFound{}
}

// WithPayload adds the payload to the delete release not found response
func (o *DeleteReleaseNotFound) WithPayload(payload *models.APIResponse) *DeleteReleaseNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release not found response
func (o *DeleteReleaseNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteReleaseInternalServerErrorCode is the HTTP code returned for type DeleteReleaseInternalServerError
const DeleteReleaseInternalServerErrorCode int = 500

/*DeleteReleaseInternalServerError Internal Server Error

swagger:response deleteReleaseInternalServerError
*/
type DeleteReleaseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteReleaseInternalServerError creates DeleteReleaseInternalServerError with default headers values
func NewDeleteReleaseInternalServerError() *DeleteReleaseInternalServerError {
	return &DeleteReleaseInternalServerError{}
}

// WithPayload adds the payload to the delete release internal server error response
func (o *DeleteReleaseInternalServerError) WithPayload(payload *models.APIResponse) *DeleteReleaseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete release internal server error response
func (o *DeleteReleaseInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteReleaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
