// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteReleaseParams creates a new DeleteReleaseParams object
// with the default values initialized.
func NewDeleteReleaseParams() DeleteReleaseParams {
	var ()
	return DeleteReleaseParams{}
}

// DeleteReleaseParams contains all the bound params for the delete release operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteRelease
type DeleteReleaseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The node labels to identify applicable clusters
	  In: query
	*/
	Labels *string
	/*ID of release to return
	  Required: true
	  In: path
	*/
	ReleaseID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *DeleteReleaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLabels, qhkLabels, _ := qs.GetOK("labels")
	if err := o.bindLabels(qLabels, qhkLabels, route.Formats); err != nil {
		res = append(res, err)
	}

	rReleaseID, rhkReleaseID, _ := route.Params.GetOK("releaseId")
	if err := o.bindReleaseID(rReleaseID, rhkReleaseID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteReleaseParams) bindLabels(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Labels = &raw

	return nil
}

func (o *DeleteReleaseParams) bindReleaseID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.ReleaseID = raw

	return nil
}
