// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetReleasesHandlerFunc turns a function with the right signature into a get releases handler
type GetReleasesHandlerFunc func(GetReleasesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetReleasesHandlerFunc) Handle(params GetReleasesParams) middleware.Responder {
	return fn(params)
}

// GetReleasesHandler interface for that can handle valid get releases params
type GetReleasesHandler interface {
	Handle(GetReleasesParams) middleware.Responder
}

// NewGetReleases creates a new http.Handler for the get releases operation
func NewGetReleases(ctx *middleware.Context, handler GetReleasesHandler) *GetReleases {
	return &GetReleases{Context: ctx, Handler: handler}
}

/*GetReleases swagger:route GET /releases releases getReleases

Returns all releases

Returns a list of releases

*/
type GetReleases struct {
	Context *middleware.Context
	Handler GetReleasesHandler
}

func (o *GetReleases) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetReleasesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
