// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon-api/api/v0/models"
)

// AddClusterCreatedCode is the HTTP code returned for type AddClusterCreated
const AddClusterCreatedCode int = 201

/*AddClusterCreated Created

swagger:response addClusterCreated
*/
type AddClusterCreated struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddClusterCreated creates AddClusterCreated with default headers values
func NewAddClusterCreated() *AddClusterCreated {
	return &AddClusterCreated{}
}

// WithPayload adds the payload to the add cluster created response
func (o *AddClusterCreated) WithPayload(payload *models.APIResponse) *AddClusterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cluster created response
func (o *AddClusterCreated) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClusterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddClusterBadRequestCode is the HTTP code returned for type AddClusterBadRequest
const AddClusterBadRequestCode int = 400

/*AddClusterBadRequest Bad Request

swagger:response addClusterBadRequest
*/
type AddClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddClusterBadRequest creates AddClusterBadRequest with default headers values
func NewAddClusterBadRequest() *AddClusterBadRequest {
	return &AddClusterBadRequest{}
}

// WithPayload adds the payload to the add cluster bad request response
func (o *AddClusterBadRequest) WithPayload(payload *models.APIResponse) *AddClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cluster bad request response
func (o *AddClusterBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddClusterUnauthorizedCode is the HTTP code returned for type AddClusterUnauthorized
const AddClusterUnauthorizedCode int = 401

/*AddClusterUnauthorized Unauthorized

swagger:response addClusterUnauthorized
*/
type AddClusterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddClusterUnauthorized creates AddClusterUnauthorized with default headers values
func NewAddClusterUnauthorized() *AddClusterUnauthorized {
	return &AddClusterUnauthorized{}
}

// WithPayload adds the payload to the add cluster unauthorized response
func (o *AddClusterUnauthorized) WithPayload(payload *models.APIResponse) *AddClusterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cluster unauthorized response
func (o *AddClusterUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddClusterInternalServerErrorCode is the HTTP code returned for type AddClusterInternalServerError
const AddClusterInternalServerErrorCode int = 500

/*AddClusterInternalServerError Internal Server Error

swagger:response addClusterInternalServerError
*/
type AddClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewAddClusterInternalServerError creates AddClusterInternalServerError with default headers values
func NewAddClusterInternalServerError() *AddClusterInternalServerError {
	return &AddClusterInternalServerError{}
}

// WithPayload adds the payload to the add cluster internal server error response
func (o *AddClusterInternalServerError) WithPayload(payload *models.APIResponse) *AddClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add cluster internal server error response
func (o *AddClusterInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
