// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// DeleteClusterOKCode is the HTTP code returned for type DeleteClusterOK
const DeleteClusterOKCode int = 200

/*DeleteClusterOK OK

swagger:response deleteClusterOK
*/
type DeleteClusterOK struct {
}

// NewDeleteClusterOK creates DeleteClusterOK with default headers values
func NewDeleteClusterOK() *DeleteClusterOK {
	return &DeleteClusterOK{}
}

// WriteResponse to the client
func (o *DeleteClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteClusterBadRequestCode is the HTTP code returned for type DeleteClusterBadRequest
const DeleteClusterBadRequestCode int = 400

/*DeleteClusterBadRequest Bad Request

swagger:response deleteClusterBadRequest
*/
type DeleteClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteClusterBadRequest creates DeleteClusterBadRequest with default headers values
func NewDeleteClusterBadRequest() *DeleteClusterBadRequest {
	return &DeleteClusterBadRequest{}
}

// WithPayload adds the payload to the delete cluster bad request response
func (o *DeleteClusterBadRequest) WithPayload(payload *models.APIResponse) *DeleteClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster bad request response
func (o *DeleteClusterBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteClusterUnauthorizedCode is the HTTP code returned for type DeleteClusterUnauthorized
const DeleteClusterUnauthorizedCode int = 401

/*DeleteClusterUnauthorized Unauthorized

swagger:response deleteClusterUnauthorized
*/
type DeleteClusterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteClusterUnauthorized creates DeleteClusterUnauthorized with default headers values
func NewDeleteClusterUnauthorized() *DeleteClusterUnauthorized {
	return &DeleteClusterUnauthorized{}
}

// WithPayload adds the payload to the delete cluster unauthorized response
func (o *DeleteClusterUnauthorized) WithPayload(payload *models.APIResponse) *DeleteClusterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster unauthorized response
func (o *DeleteClusterUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteClusterNotFoundCode is the HTTP code returned for type DeleteClusterNotFound
const DeleteClusterNotFoundCode int = 404

/*DeleteClusterNotFound The specified resource was not found

swagger:response deleteClusterNotFound
*/
type DeleteClusterNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteClusterNotFound creates DeleteClusterNotFound with default headers values
func NewDeleteClusterNotFound() *DeleteClusterNotFound {
	return &DeleteClusterNotFound{}
}

// WithPayload adds the payload to the delete cluster not found response
func (o *DeleteClusterNotFound) WithPayload(payload *models.APIResponse) *DeleteClusterNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster not found response
func (o *DeleteClusterNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteClusterInternalServerErrorCode is the HTTP code returned for type DeleteClusterInternalServerError
const DeleteClusterInternalServerErrorCode int = 500

/*DeleteClusterInternalServerError Internal Server Error

swagger:response deleteClusterInternalServerError
*/
type DeleteClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteClusterInternalServerError creates DeleteClusterInternalServerError with default headers values
func NewDeleteClusterInternalServerError() *DeleteClusterInternalServerError {
	return &DeleteClusterInternalServerError{}
}

// WithPayload adds the payload to the delete cluster internal server error response
func (o *DeleteClusterInternalServerError) WithPayload(payload *models.APIResponse) *DeleteClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete cluster internal server error response
func (o *DeleteClusterInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
