// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/optikon/api/api/v0/models"
)

// GetClustersOKCode is the HTTP code returned for type GetClustersOK
const GetClustersOKCode int = 200

/*GetClustersOK OK

swagger:response getClustersOK
*/
type GetClustersOK struct {

	/*
	  In: Body
	*/
	Payload models.GetClustersOKBody `json:"body,omitempty"`
}

// NewGetClustersOK creates GetClustersOK with default headers values
func NewGetClustersOK() *GetClustersOK {
	return &GetClustersOK{}
}

// WithPayload adds the payload to the get clusters o k response
func (o *GetClustersOK) WithPayload(payload models.GetClustersOKBody) *GetClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters o k response
func (o *GetClustersOK) SetPayload(payload models.GetClustersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetClustersOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetClustersBadRequestCode is the HTTP code returned for type GetClustersBadRequest
const GetClustersBadRequestCode int = 400

/*GetClustersBadRequest Bad Request

swagger:response getClustersBadRequest
*/
type GetClustersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetClustersBadRequest creates GetClustersBadRequest with default headers values
func NewGetClustersBadRequest() *GetClustersBadRequest {
	return &GetClustersBadRequest{}
}

// WithPayload adds the payload to the get clusters bad request response
func (o *GetClustersBadRequest) WithPayload(payload *models.APIResponse) *GetClustersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters bad request response
func (o *GetClustersBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersUnauthorizedCode is the HTTP code returned for type GetClustersUnauthorized
const GetClustersUnauthorizedCode int = 401

/*GetClustersUnauthorized Unauthorized

swagger:response getClustersUnauthorized
*/
type GetClustersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetClustersUnauthorized creates GetClustersUnauthorized with default headers values
func NewGetClustersUnauthorized() *GetClustersUnauthorized {
	return &GetClustersUnauthorized{}
}

// WithPayload adds the payload to the get clusters unauthorized response
func (o *GetClustersUnauthorized) WithPayload(payload *models.APIResponse) *GetClustersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters unauthorized response
func (o *GetClustersUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersInternalServerErrorCode is the HTTP code returned for type GetClustersInternalServerError
const GetClustersInternalServerErrorCode int = 500

/*GetClustersInternalServerError Internal Server Error

swagger:response getClustersInternalServerError
*/
type GetClustersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetClustersInternalServerError creates GetClustersInternalServerError with default headers values
func NewGetClustersInternalServerError() *GetClustersInternalServerError {
	return &GetClustersInternalServerError{}
}

// WithPayload adds the payload to the get clusters internal server error response
func (o *GetClustersInternalServerError) WithPayload(payload *models.APIResponse) *GetClustersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters internal server error response
func (o *GetClustersInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
