// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// GetClusterByIDReader is a Reader for the GetClusterByID structure.
type GetClusterByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetClusterByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetClusterByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetClusterByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetClusterByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetClusterByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetClusterByIDOK creates a GetClusterByIDOK with default headers values
func NewGetClusterByIDOK() *GetClusterByIDOK {
	return &GetClusterByIDOK{}
}

/*GetClusterByIDOK handles this case with default header values.

OK
*/
type GetClusterByIDOK struct {
	Payload *models.IoK8sClusterRegistryPkgApisClusterregistryV1alpha1Cluster
}

func (o *GetClusterByIDOK) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}][%d] getClusterByIdOK  %+v", 200, o.Payload)
}

func (o *GetClusterByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IoK8sClusterRegistryPkgApisClusterregistryV1alpha1Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterByIDBadRequest creates a GetClusterByIDBadRequest with default headers values
func NewGetClusterByIDBadRequest() *GetClusterByIDBadRequest {
	return &GetClusterByIDBadRequest{}
}

/*GetClusterByIDBadRequest handles this case with default header values.

Bad Request
*/
type GetClusterByIDBadRequest struct {
	Payload *models.APIResponse
}

func (o *GetClusterByIDBadRequest) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}][%d] getClusterByIdBadRequest  %+v", 400, o.Payload)
}

func (o *GetClusterByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterByIDUnauthorized creates a GetClusterByIDUnauthorized with default headers values
func NewGetClusterByIDUnauthorized() *GetClusterByIDUnauthorized {
	return &GetClusterByIDUnauthorized{}
}

/*GetClusterByIDUnauthorized handles this case with default header values.

Unauthorized
*/
type GetClusterByIDUnauthorized struct {
	Payload *models.APIResponse
}

func (o *GetClusterByIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}][%d] getClusterByIdUnauthorized  %+v", 401, o.Payload)
}

func (o *GetClusterByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterByIDNotFound creates a GetClusterByIDNotFound with default headers values
func NewGetClusterByIDNotFound() *GetClusterByIDNotFound {
	return &GetClusterByIDNotFound{}
}

/*GetClusterByIDNotFound handles this case with default header values.

The specified resource was not found
*/
type GetClusterByIDNotFound struct {
	Payload *models.APIResponse
}

func (o *GetClusterByIDNotFound) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}][%d] getClusterByIdNotFound  %+v", 404, o.Payload)
}

func (o *GetClusterByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterByIDInternalServerError creates a GetClusterByIDInternalServerError with default headers values
func NewGetClusterByIDInternalServerError() *GetClusterByIDInternalServerError {
	return &GetClusterByIDInternalServerError{}
}

/*GetClusterByIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetClusterByIDInternalServerError struct {
	Payload *models.APIResponse
}

func (o *GetClusterByIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /clusters/{clusterId}][%d] getClusterByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetClusterByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
