// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/optikon/api/api/v0/models"
)

// AddReleasesReader is a Reader for the AddReleases structure.
type AddReleasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddReleasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddReleasesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddReleasesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAddReleasesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewAddReleasesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddReleasesCreated creates a AddReleasesCreated with default headers values
func NewAddReleasesCreated() *AddReleasesCreated {
	return &AddReleasesCreated{}
}

/*AddReleasesCreated handles this case with default header values.

Created
*/
type AddReleasesCreated struct {
	Payload *models.APIResponse
}

func (o *AddReleasesCreated) Error() string {
	return fmt.Sprintf("[POST /releases][%d] addReleasesCreated  %+v", 201, o.Payload)
}

func (o *AddReleasesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddReleasesBadRequest creates a AddReleasesBadRequest with default headers values
func NewAddReleasesBadRequest() *AddReleasesBadRequest {
	return &AddReleasesBadRequest{}
}

/*AddReleasesBadRequest handles this case with default header values.

Bad Request
*/
type AddReleasesBadRequest struct {
	Payload *models.APIResponse
}

func (o *AddReleasesBadRequest) Error() string {
	return fmt.Sprintf("[POST /releases][%d] addReleasesBadRequest  %+v", 400, o.Payload)
}

func (o *AddReleasesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddReleasesUnauthorized creates a AddReleasesUnauthorized with default headers values
func NewAddReleasesUnauthorized() *AddReleasesUnauthorized {
	return &AddReleasesUnauthorized{}
}

/*AddReleasesUnauthorized handles this case with default header values.

Unauthorized
*/
type AddReleasesUnauthorized struct {
	Payload *models.APIResponse
}

func (o *AddReleasesUnauthorized) Error() string {
	return fmt.Sprintf("[POST /releases][%d] addReleasesUnauthorized  %+v", 401, o.Payload)
}

func (o *AddReleasesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddReleasesInternalServerError creates a AddReleasesInternalServerError with default headers values
func NewAddReleasesInternalServerError() *AddReleasesInternalServerError {
	return &AddReleasesInternalServerError{}
}

/*AddReleasesInternalServerError handles this case with default header values.

Internal Server Error
*/
type AddReleasesInternalServerError struct {
	Payload *models.APIResponse
}

func (o *AddReleasesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /releases][%d] addReleasesInternalServerError  %+v", 500, o.Payload)
}

func (o *AddReleasesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
