// Code generated by go-swagger; DO NOT EDIT.

package releases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteReleaseParams creates a new DeleteReleaseParams object
// with the default values initialized.
func NewDeleteReleaseParams() *DeleteReleaseParams {
	var ()
	return &DeleteReleaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteReleaseParamsWithTimeout creates a new DeleteReleaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteReleaseParamsWithTimeout(timeout time.Duration) *DeleteReleaseParams {
	var ()
	return &DeleteReleaseParams{

		timeout: timeout,
	}
}

// NewDeleteReleaseParamsWithContext creates a new DeleteReleaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteReleaseParamsWithContext(ctx context.Context) *DeleteReleaseParams {
	var ()
	return &DeleteReleaseParams{

		Context: ctx,
	}
}

// NewDeleteReleaseParamsWithHTTPClient creates a new DeleteReleaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteReleaseParamsWithHTTPClient(client *http.Client) *DeleteReleaseParams {
	var ()
	return &DeleteReleaseParams{
		HTTPClient: client,
	}
}

/*DeleteReleaseParams contains all the parameters to send to the API endpoint
for the delete release operation typically these are written to a http.Request
*/
type DeleteReleaseParams struct {

	/*Labels
	  The node labels to identify applicable clusters

	*/
	Labels *string
	/*ReleaseID
	  ID of release to return

	*/
	ReleaseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete release params
func (o *DeleteReleaseParams) WithTimeout(timeout time.Duration) *DeleteReleaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete release params
func (o *DeleteReleaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete release params
func (o *DeleteReleaseParams) WithContext(ctx context.Context) *DeleteReleaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete release params
func (o *DeleteReleaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete release params
func (o *DeleteReleaseParams) WithHTTPClient(client *http.Client) *DeleteReleaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete release params
func (o *DeleteReleaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLabels adds the labels to the delete release params
func (o *DeleteReleaseParams) WithLabels(labels *string) *DeleteReleaseParams {
	o.SetLabels(labels)
	return o
}

// SetLabels adds the labels to the delete release params
func (o *DeleteReleaseParams) SetLabels(labels *string) {
	o.Labels = labels
}

// WithReleaseID adds the releaseID to the delete release params
func (o *DeleteReleaseParams) WithReleaseID(releaseID string) *DeleteReleaseParams {
	o.SetReleaseID(releaseID)
	return o
}

// SetReleaseID adds the releaseId to the delete release params
func (o *DeleteReleaseParams) SetReleaseID(releaseID string) {
	o.ReleaseID = releaseID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteReleaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Labels != nil {

		// query param labels
		var qrLabels string
		if o.Labels != nil {
			qrLabels = *o.Labels
		}
		qLabels := qrLabels
		if qLabels != "" {
			if err := r.SetQueryParam("labels", qLabels); err != nil {
				return err
			}
		}

	}

	// path param releaseId
	if err := r.SetPathParam("releaseId", o.ReleaseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
