// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"wwwin-github.cisco.com/edge/optikon/api/v0/server/restapi/operations/charts"
	"wwwin-github.cisco.com/edge/optikon/api/v0/server/restapi/operations/clusters"
)

// NewOptikonAPI creates a new Optikon instance
func NewOptikonAPI(spec *loads.Document) *OptikonAPI {
	return &OptikonAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ChartsAddChartsHandler: charts.AddChartsHandlerFunc(func(params charts.AddChartsParams) middleware.Responder {
			return middleware.NotImplemented("operation ChartsAddCharts has not yet been implemented")
		}),
		ClustersAddClusterHandler: clusters.AddClusterHandlerFunc(func(params clusters.AddClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersAddCluster has not yet been implemented")
		}),
		ChartsDeleteChartHandler: charts.DeleteChartHandlerFunc(func(params charts.DeleteChartParams) middleware.Responder {
			return middleware.NotImplemented("operation ChartsDeleteChart has not yet been implemented")
		}),
		ClustersDeleteClusterHandler: clusters.DeleteClusterHandlerFunc(func(params clusters.DeleteClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersDeleteCluster has not yet been implemented")
		}),
		ChartsGetChartByIDHandler: charts.GetChartByIDHandlerFunc(func(params charts.GetChartByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ChartsGetChartByID has not yet been implemented")
		}),
		ChartsGetChartsHandler: charts.GetChartsHandlerFunc(func(params charts.GetChartsParams) middleware.Responder {
			return middleware.NotImplemented("operation ChartsGetCharts has not yet been implemented")
		}),
		ClustersGetClusterByIDHandler: clusters.GetClusterByIDHandlerFunc(func(params clusters.GetClusterByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersGetClusterByID has not yet been implemented")
		}),
		ClustersGetClustersHandler: clusters.GetClustersHandlerFunc(func(params clusters.GetClustersParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersGetClusters has not yet been implemented")
		}),
		ChartsUpdateChartHandler: charts.UpdateChartHandlerFunc(func(params charts.UpdateChartParams) middleware.Responder {
			return middleware.NotImplemented("operation ChartsUpdateChart has not yet been implemented")
		}),
		ClustersUpdateClusterHandler: clusters.UpdateClusterHandlerFunc(func(params clusters.UpdateClusterParams) middleware.Responder {
			return middleware.NotImplemented("operation ClustersUpdateCluster has not yet been implemented")
		}),
	}
}

/*OptikonAPI Optikon is an edge computing API for Kubernetes. It exposes Helm and the cluster registry for a comprehensive UI */
type OptikonAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// ChartsAddChartsHandler sets the operation handler for the add charts operation
	ChartsAddChartsHandler charts.AddChartsHandler
	// ClustersAddClusterHandler sets the operation handler for the add cluster operation
	ClustersAddClusterHandler clusters.AddClusterHandler
	// ChartsDeleteChartHandler sets the operation handler for the delete chart operation
	ChartsDeleteChartHandler charts.DeleteChartHandler
	// ClustersDeleteClusterHandler sets the operation handler for the delete cluster operation
	ClustersDeleteClusterHandler clusters.DeleteClusterHandler
	// ChartsGetChartByIDHandler sets the operation handler for the get chart by Id operation
	ChartsGetChartByIDHandler charts.GetChartByIDHandler
	// ChartsGetChartsHandler sets the operation handler for the get charts operation
	ChartsGetChartsHandler charts.GetChartsHandler
	// ClustersGetClusterByIDHandler sets the operation handler for the get cluster by Id operation
	ClustersGetClusterByIDHandler clusters.GetClusterByIDHandler
	// ClustersGetClustersHandler sets the operation handler for the get clusters operation
	ClustersGetClustersHandler clusters.GetClustersHandler
	// ChartsUpdateChartHandler sets the operation handler for the update chart operation
	ChartsUpdateChartHandler charts.UpdateChartHandler
	// ClustersUpdateClusterHandler sets the operation handler for the update cluster operation
	ClustersUpdateClusterHandler clusters.UpdateClusterHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *OptikonAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *OptikonAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *OptikonAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *OptikonAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *OptikonAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *OptikonAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *OptikonAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the OptikonAPI
func (o *OptikonAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ChartsAddChartsHandler == nil {
		unregistered = append(unregistered, "charts.AddChartsHandler")
	}

	if o.ClustersAddClusterHandler == nil {
		unregistered = append(unregistered, "clusters.AddClusterHandler")
	}

	if o.ChartsDeleteChartHandler == nil {
		unregistered = append(unregistered, "charts.DeleteChartHandler")
	}

	if o.ClustersDeleteClusterHandler == nil {
		unregistered = append(unregistered, "clusters.DeleteClusterHandler")
	}

	if o.ChartsGetChartByIDHandler == nil {
		unregistered = append(unregistered, "charts.GetChartByIDHandler")
	}

	if o.ChartsGetChartsHandler == nil {
		unregistered = append(unregistered, "charts.GetChartsHandler")
	}

	if o.ClustersGetClusterByIDHandler == nil {
		unregistered = append(unregistered, "clusters.GetClusterByIDHandler")
	}

	if o.ClustersGetClustersHandler == nil {
		unregistered = append(unregistered, "clusters.GetClustersHandler")
	}

	if o.ChartsUpdateChartHandler == nil {
		unregistered = append(unregistered, "charts.UpdateChartHandler")
	}

	if o.ClustersUpdateClusterHandler == nil {
		unregistered = append(unregistered, "clusters.UpdateClusterHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *OptikonAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *OptikonAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *OptikonAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *OptikonAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *OptikonAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *OptikonAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the optikon API
func (o *OptikonAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *OptikonAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/charts"] = charts.NewAddCharts(o.context, o.ChartsAddChartsHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/clusters"] = clusters.NewAddCluster(o.context, o.ClustersAddClusterHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/charts/{chartId}"] = charts.NewDeleteChart(o.context, o.ChartsDeleteChartHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/clusters/{clusterId}"] = clusters.NewDeleteCluster(o.context, o.ClustersDeleteClusterHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/charts/{chartId}"] = charts.NewGetChartByID(o.context, o.ChartsGetChartByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/charts"] = charts.NewGetCharts(o.context, o.ChartsGetChartsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clusters/{clusterId}"] = clusters.NewGetClusterByID(o.context, o.ClustersGetClusterByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clusters"] = clusters.NewGetClusters(o.context, o.ClustersGetClustersHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/charts/{chartId}"] = charts.NewUpdateChart(o.context, o.ChartsUpdateChartHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/clusters/{clusterId}"] = clusters.NewUpdateCluster(o.context, o.ClustersUpdateClusterHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *OptikonAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middelware as you see fit
func (o *OptikonAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}
