// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// NewAddChartsParams creates a new AddChartsParams object
// with the default values initialized.
func NewAddChartsParams() *AddChartsParams {
	var ()
	return &AddChartsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddChartsParamsWithTimeout creates a new AddChartsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddChartsParamsWithTimeout(timeout time.Duration) *AddChartsParams {
	var ()
	return &AddChartsParams{

		timeout: timeout,
	}
}

// NewAddChartsParamsWithContext creates a new AddChartsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddChartsParamsWithContext(ctx context.Context) *AddChartsParams {
	var ()
	return &AddChartsParams{

		Context: ctx,
	}
}

// NewAddChartsParamsWithHTTPClient creates a new AddChartsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddChartsParamsWithHTTPClient(client *http.Client) *AddChartsParams {
	var ()
	return &AddChartsParams{
		HTTPClient: client,
	}
}

/*AddChartsParams contains all the parameters to send to the API endpoint
for the add charts operation typically these are written to a http.Request
*/
type AddChartsParams struct {

	/*Body*/
	Body *models.ChartChart

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add charts params
func (o *AddChartsParams) WithTimeout(timeout time.Duration) *AddChartsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add charts params
func (o *AddChartsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add charts params
func (o *AddChartsParams) WithContext(ctx context.Context) *AddChartsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add charts params
func (o *AddChartsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add charts params
func (o *AddChartsParams) WithHTTPClient(client *http.Client) *AddChartsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add charts params
func (o *AddChartsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add charts params
func (o *AddChartsParams) WithBody(body *models.ChartChart) *AddChartsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add charts params
func (o *AddChartsParams) SetBody(body *models.ChartChart) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddChartsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
