// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// AddChartsReader is a Reader for the AddCharts structure.
type AddChartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddChartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddChartsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewAddChartsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewAddChartsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewAddChartsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAddChartsCreated creates a AddChartsCreated with default headers values
func NewAddChartsCreated() *AddChartsCreated {
	return &AddChartsCreated{}
}

/*AddChartsCreated handles this case with default header values.

Created
*/
type AddChartsCreated struct {
	Payload *models.APIResponse
}

func (o *AddChartsCreated) Error() string {
	return fmt.Sprintf("[POST /charts][%d] addChartsCreated  %+v", 201, o.Payload)
}

func (o *AddChartsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddChartsBadRequest creates a AddChartsBadRequest with default headers values
func NewAddChartsBadRequest() *AddChartsBadRequest {
	return &AddChartsBadRequest{}
}

/*AddChartsBadRequest handles this case with default header values.

Bad Request
*/
type AddChartsBadRequest struct {
	Payload *models.APIResponse
}

func (o *AddChartsBadRequest) Error() string {
	return fmt.Sprintf("[POST /charts][%d] addChartsBadRequest  %+v", 400, o.Payload)
}

func (o *AddChartsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddChartsUnauthorized creates a AddChartsUnauthorized with default headers values
func NewAddChartsUnauthorized() *AddChartsUnauthorized {
	return &AddChartsUnauthorized{}
}

/*AddChartsUnauthorized handles this case with default header values.

Unauthorized
*/
type AddChartsUnauthorized struct {
	Payload *models.APIResponse
}

func (o *AddChartsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /charts][%d] addChartsUnauthorized  %+v", 401, o.Payload)
}

func (o *AddChartsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddChartsInternalServerError creates a AddChartsInternalServerError with default headers values
func NewAddChartsInternalServerError() *AddChartsInternalServerError {
	return &AddChartsInternalServerError{}
}

/*AddChartsInternalServerError handles this case with default header values.

Internal Server Error
*/
type AddChartsInternalServerError struct {
	Payload *models.APIResponse
}

func (o *AddChartsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /charts][%d] addChartsInternalServerError  %+v", 500, o.Payload)
}

func (o *AddChartsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
