// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteChartParams creates a new DeleteChartParams object
// with the default values initialized.
func NewDeleteChartParams() *DeleteChartParams {
	var ()
	return &DeleteChartParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteChartParamsWithTimeout creates a new DeleteChartParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteChartParamsWithTimeout(timeout time.Duration) *DeleteChartParams {
	var ()
	return &DeleteChartParams{

		timeout: timeout,
	}
}

// NewDeleteChartParamsWithContext creates a new DeleteChartParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteChartParamsWithContext(ctx context.Context) *DeleteChartParams {
	var ()
	return &DeleteChartParams{

		Context: ctx,
	}
}

// NewDeleteChartParamsWithHTTPClient creates a new DeleteChartParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteChartParamsWithHTTPClient(client *http.Client) *DeleteChartParams {
	var ()
	return &DeleteChartParams{
		HTTPClient: client,
	}
}

/*DeleteChartParams contains all the parameters to send to the API endpoint
for the delete chart operation typically these are written to a http.Request
*/
type DeleteChartParams struct {

	/*ChartID
	  ID of chart to return

	*/
	ChartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete chart params
func (o *DeleteChartParams) WithTimeout(timeout time.Duration) *DeleteChartParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete chart params
func (o *DeleteChartParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete chart params
func (o *DeleteChartParams) WithContext(ctx context.Context) *DeleteChartParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete chart params
func (o *DeleteChartParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete chart params
func (o *DeleteChartParams) WithHTTPClient(client *http.Client) *DeleteChartParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete chart params
func (o *DeleteChartParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChartID adds the chartID to the delete chart params
func (o *DeleteChartParams) WithChartID(chartID string) *DeleteChartParams {
	o.SetChartID(chartID)
	return o
}

// SetChartID adds the chartId to the delete chart params
func (o *DeleteChartParams) SetChartID(chartID string) {
	o.ChartID = chartID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteChartParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param chartId
	if err := r.SetPathParam("chartId", o.ChartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
