// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChartByIDParams creates a new GetChartByIDParams object
// with the default values initialized.
func NewGetChartByIDParams() *GetChartByIDParams {
	var ()
	return &GetChartByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChartByIDParamsWithTimeout creates a new GetChartByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChartByIDParamsWithTimeout(timeout time.Duration) *GetChartByIDParams {
	var ()
	return &GetChartByIDParams{

		timeout: timeout,
	}
}

// NewGetChartByIDParamsWithContext creates a new GetChartByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChartByIDParamsWithContext(ctx context.Context) *GetChartByIDParams {
	var ()
	return &GetChartByIDParams{

		Context: ctx,
	}
}

// NewGetChartByIDParamsWithHTTPClient creates a new GetChartByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChartByIDParamsWithHTTPClient(client *http.Client) *GetChartByIDParams {
	var ()
	return &GetChartByIDParams{
		HTTPClient: client,
	}
}

/*GetChartByIDParams contains all the parameters to send to the API endpoint
for the get chart by Id operation typically these are written to a http.Request
*/
type GetChartByIDParams struct {

	/*ChartID
	  ID of chart to return

	*/
	ChartID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get chart by Id params
func (o *GetChartByIDParams) WithTimeout(timeout time.Duration) *GetChartByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get chart by Id params
func (o *GetChartByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get chart by Id params
func (o *GetChartByIDParams) WithContext(ctx context.Context) *GetChartByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get chart by Id params
func (o *GetChartByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get chart by Id params
func (o *GetChartByIDParams) WithHTTPClient(client *http.Client) *GetChartByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get chart by Id params
func (o *GetChartByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChartID adds the chartID to the get chart by Id params
func (o *GetChartByIDParams) WithChartID(chartID string) *GetChartByIDParams {
	o.SetChartID(chartID)
	return o
}

// SetChartID adds the chartId to the get chart by Id params
func (o *GetChartByIDParams) SetChartID(chartID string) {
	o.ChartID = chartID
}

// WriteToRequest writes these params to a swagger request
func (o *GetChartByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param chartId
	if err := r.SetPathParam("chartId", o.ChartID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
