// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"wwwin-github.cisco.com/edge/optikon-api/api/v0/models"
)

// GetChartsReader is a Reader for the GetCharts structure.
type GetChartsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetChartsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetChartsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetChartsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetChartsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetChartsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetChartsOK creates a GetChartsOK with default headers values
func NewGetChartsOK() *GetChartsOK {
	return &GetChartsOK{}
}

/*GetChartsOK handles this case with default header values.

OK
*/
type GetChartsOK struct {
	Payload models.GetChartsOKBody
}

func (o *GetChartsOK) Error() string {
	return fmt.Sprintf("[GET /charts][%d] getChartsOK  %+v", 200, o.Payload)
}

func (o *GetChartsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartsBadRequest creates a GetChartsBadRequest with default headers values
func NewGetChartsBadRequest() *GetChartsBadRequest {
	return &GetChartsBadRequest{}
}

/*GetChartsBadRequest handles this case with default header values.

Bad Request
*/
type GetChartsBadRequest struct {
	Payload *models.APIResponse
}

func (o *GetChartsBadRequest) Error() string {
	return fmt.Sprintf("[GET /charts][%d] getChartsBadRequest  %+v", 400, o.Payload)
}

func (o *GetChartsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartsUnauthorized creates a GetChartsUnauthorized with default headers values
func NewGetChartsUnauthorized() *GetChartsUnauthorized {
	return &GetChartsUnauthorized{}
}

/*GetChartsUnauthorized handles this case with default header values.

Unauthorized
*/
type GetChartsUnauthorized struct {
	Payload *models.APIResponse
}

func (o *GetChartsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /charts][%d] getChartsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetChartsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetChartsInternalServerError creates a GetChartsInternalServerError with default headers values
func NewGetChartsInternalServerError() *GetChartsInternalServerError {
	return &GetChartsInternalServerError{}
}

/*GetChartsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetChartsInternalServerError struct {
	Payload *models.APIResponse
}

func (o *GetChartsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /charts][%d] getChartsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetChartsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
