// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChartsParams creates a new GetChartsParams object
// with the default values initialized.
func NewGetChartsParams() *GetChartsParams {

	return &GetChartsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChartsParamsWithTimeout creates a new GetChartsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChartsParamsWithTimeout(timeout time.Duration) *GetChartsParams {

	return &GetChartsParams{

		timeout: timeout,
	}
}

// NewGetChartsParamsWithContext creates a new GetChartsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChartsParamsWithContext(ctx context.Context) *GetChartsParams {

	return &GetChartsParams{

		Context: ctx,
	}
}

// NewGetChartsParamsWithHTTPClient creates a new GetChartsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChartsParamsWithHTTPClient(client *http.Client) *GetChartsParams {

	return &GetChartsParams{
		HTTPClient: client,
	}
}

/*GetChartsParams contains all the parameters to send to the API endpoint
for the get charts operation typically these are written to a http.Request
*/
type GetChartsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get charts params
func (o *GetChartsParams) WithTimeout(timeout time.Duration) *GetChartsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get charts params
func (o *GetChartsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get charts params
func (o *GetChartsParams) WithContext(ctx context.Context) *GetChartsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get charts params
func (o *GetChartsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get charts params
func (o *GetChartsParams) WithHTTPClient(client *http.Client) *GetChartsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get charts params
func (o *GetChartsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetChartsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
