// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddChartsHandlerFunc turns a function with the right signature into a add charts handler
type AddChartsHandlerFunc func(AddChartsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddChartsHandlerFunc) Handle(params AddChartsParams) middleware.Responder {
	return fn(params)
}

// AddChartsHandler interface for that can handle valid add charts params
type AddChartsHandler interface {
	Handle(AddChartsParams) middleware.Responder
}

// NewAddCharts creates a new http.Handler for the add charts operation
func NewAddCharts(ctx *middleware.Context, handler AddChartsHandler) *AddCharts {
	return &AddCharts{Context: ctx, Handler: handler}
}

/*AddCharts swagger:route POST /charts charts addCharts

Add a new cluster to optikon

*/
type AddCharts struct {
	Context *middleware.Context
	Handler AddChartsHandler
}

func (o *AddCharts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddChartsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
