// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteChartHandlerFunc turns a function with the right signature into a delete chart handler
type DeleteChartHandlerFunc func(DeleteChartParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteChartHandlerFunc) Handle(params DeleteChartParams) middleware.Responder {
	return fn(params)
}

// DeleteChartHandler interface for that can handle valid delete chart params
type DeleteChartHandler interface {
	Handle(DeleteChartParams) middleware.Responder
}

// NewDeleteChart creates a new http.Handler for the delete chart operation
func NewDeleteChart(ctx *middleware.Context, handler DeleteChartHandler) *DeleteChart {
	return &DeleteChart{Context: ctx, Handler: handler}
}

/*DeleteChart swagger:route DELETE /charts/{chartId} charts deleteChart

Delete chart by ID

*/
type DeleteChart struct {
	Context *middleware.Context
	Handler DeleteChartHandler
}

func (o *DeleteChart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteChartParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
