// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// DeleteChartOKCode is the HTTP code returned for type DeleteChartOK
const DeleteChartOKCode int = 200

/*DeleteChartOK OK

swagger:response deleteChartOK
*/
type DeleteChartOK struct {
}

// NewDeleteChartOK creates DeleteChartOK with default headers values
func NewDeleteChartOK() *DeleteChartOK {
	return &DeleteChartOK{}
}

// WriteResponse to the client
func (o *DeleteChartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteChartBadRequestCode is the HTTP code returned for type DeleteChartBadRequest
const DeleteChartBadRequestCode int = 400

/*DeleteChartBadRequest Bad Request

swagger:response deleteChartBadRequest
*/
type DeleteChartBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteChartBadRequest creates DeleteChartBadRequest with default headers values
func NewDeleteChartBadRequest() *DeleteChartBadRequest {
	return &DeleteChartBadRequest{}
}

// WithPayload adds the payload to the delete chart bad request response
func (o *DeleteChartBadRequest) WithPayload(payload *models.APIResponse) *DeleteChartBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chart bad request response
func (o *DeleteChartBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChartBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChartUnauthorizedCode is the HTTP code returned for type DeleteChartUnauthorized
const DeleteChartUnauthorizedCode int = 401

/*DeleteChartUnauthorized Unauthorized

swagger:response deleteChartUnauthorized
*/
type DeleteChartUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteChartUnauthorized creates DeleteChartUnauthorized with default headers values
func NewDeleteChartUnauthorized() *DeleteChartUnauthorized {
	return &DeleteChartUnauthorized{}
}

// WithPayload adds the payload to the delete chart unauthorized response
func (o *DeleteChartUnauthorized) WithPayload(payload *models.APIResponse) *DeleteChartUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chart unauthorized response
func (o *DeleteChartUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChartUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChartNotFoundCode is the HTTP code returned for type DeleteChartNotFound
const DeleteChartNotFoundCode int = 404

/*DeleteChartNotFound The specified resource was not found

swagger:response deleteChartNotFound
*/
type DeleteChartNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteChartNotFound creates DeleteChartNotFound with default headers values
func NewDeleteChartNotFound() *DeleteChartNotFound {
	return &DeleteChartNotFound{}
}

// WithPayload adds the payload to the delete chart not found response
func (o *DeleteChartNotFound) WithPayload(payload *models.APIResponse) *DeleteChartNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chart not found response
func (o *DeleteChartNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChartNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteChartInternalServerErrorCode is the HTTP code returned for type DeleteChartInternalServerError
const DeleteChartInternalServerErrorCode int = 500

/*DeleteChartInternalServerError Internal Server Error

swagger:response deleteChartInternalServerError
*/
type DeleteChartInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDeleteChartInternalServerError creates DeleteChartInternalServerError with default headers values
func NewDeleteChartInternalServerError() *DeleteChartInternalServerError {
	return &DeleteChartInternalServerError{}
}

// WithPayload adds the payload to the delete chart internal server error response
func (o *DeleteChartInternalServerError) WithPayload(payload *models.APIResponse) *DeleteChartInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete chart internal server error response
func (o *DeleteChartInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteChartInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
