// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// GetChartsOKCode is the HTTP code returned for type GetChartsOK
const GetChartsOKCode int = 200

/*GetChartsOK OK

swagger:response getChartsOK
*/
type GetChartsOK struct {

	/*
	  In: Body
	*/
	Payload models.GetChartsOKBody `json:"body,omitempty"`
}

// NewGetChartsOK creates GetChartsOK with default headers values
func NewGetChartsOK() *GetChartsOK {
	return &GetChartsOK{}
}

// WithPayload adds the payload to the get charts o k response
func (o *GetChartsOK) WithPayload(payload models.GetChartsOKBody) *GetChartsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get charts o k response
func (o *GetChartsOK) SetPayload(payload models.GetChartsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetChartsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetChartsBadRequestCode is the HTTP code returned for type GetChartsBadRequest
const GetChartsBadRequestCode int = 400

/*GetChartsBadRequest Bad Request

swagger:response getChartsBadRequest
*/
type GetChartsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetChartsBadRequest creates GetChartsBadRequest with default headers values
func NewGetChartsBadRequest() *GetChartsBadRequest {
	return &GetChartsBadRequest{}
}

// WithPayload adds the payload to the get charts bad request response
func (o *GetChartsBadRequest) WithPayload(payload *models.APIResponse) *GetChartsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get charts bad request response
func (o *GetChartsBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChartsUnauthorizedCode is the HTTP code returned for type GetChartsUnauthorized
const GetChartsUnauthorizedCode int = 401

/*GetChartsUnauthorized Unauthorized

swagger:response getChartsUnauthorized
*/
type GetChartsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetChartsUnauthorized creates GetChartsUnauthorized with default headers values
func NewGetChartsUnauthorized() *GetChartsUnauthorized {
	return &GetChartsUnauthorized{}
}

// WithPayload adds the payload to the get charts unauthorized response
func (o *GetChartsUnauthorized) WithPayload(payload *models.APIResponse) *GetChartsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get charts unauthorized response
func (o *GetChartsUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChartsInternalServerErrorCode is the HTTP code returned for type GetChartsInternalServerError
const GetChartsInternalServerErrorCode int = 500

/*GetChartsInternalServerError Internal Server Error

swagger:response getChartsInternalServerError
*/
type GetChartsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetChartsInternalServerError creates GetChartsInternalServerError with default headers values
func NewGetChartsInternalServerError() *GetChartsInternalServerError {
	return &GetChartsInternalServerError{}
}

// WithPayload adds the payload to the get charts internal server error response
func (o *GetChartsInternalServerError) WithPayload(payload *models.APIResponse) *GetChartsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get charts internal server error response
func (o *GetChartsInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChartsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
