// Code generated by go-swagger; DO NOT EDIT.

package charts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"wwwin-github.cisco.com/edge/optikon/api/v0/models"
)

// UpdateChartOKCode is the HTTP code returned for type UpdateChartOK
const UpdateChartOKCode int = 200

/*UpdateChartOK OK

swagger:response updateChartOK
*/
type UpdateChartOK struct {
}

// NewUpdateChartOK creates UpdateChartOK with default headers values
func NewUpdateChartOK() *UpdateChartOK {
	return &UpdateChartOK{}
}

// WriteResponse to the client
func (o *UpdateChartOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateChartBadRequestCode is the HTTP code returned for type UpdateChartBadRequest
const UpdateChartBadRequestCode int = 400

/*UpdateChartBadRequest Bad Request

swagger:response updateChartBadRequest
*/
type UpdateChartBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateChartBadRequest creates UpdateChartBadRequest with default headers values
func NewUpdateChartBadRequest() *UpdateChartBadRequest {
	return &UpdateChartBadRequest{}
}

// WithPayload adds the payload to the update chart bad request response
func (o *UpdateChartBadRequest) WithPayload(payload *models.APIResponse) *UpdateChartBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update chart bad request response
func (o *UpdateChartBadRequest) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateChartBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateChartUnauthorizedCode is the HTTP code returned for type UpdateChartUnauthorized
const UpdateChartUnauthorizedCode int = 401

/*UpdateChartUnauthorized Unauthorized

swagger:response updateChartUnauthorized
*/
type UpdateChartUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateChartUnauthorized creates UpdateChartUnauthorized with default headers values
func NewUpdateChartUnauthorized() *UpdateChartUnauthorized {
	return &UpdateChartUnauthorized{}
}

// WithPayload adds the payload to the update chart unauthorized response
func (o *UpdateChartUnauthorized) WithPayload(payload *models.APIResponse) *UpdateChartUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update chart unauthorized response
func (o *UpdateChartUnauthorized) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateChartUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateChartNotFoundCode is the HTTP code returned for type UpdateChartNotFound
const UpdateChartNotFoundCode int = 404

/*UpdateChartNotFound The specified resource was not found

swagger:response updateChartNotFound
*/
type UpdateChartNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateChartNotFound creates UpdateChartNotFound with default headers values
func NewUpdateChartNotFound() *UpdateChartNotFound {
	return &UpdateChartNotFound{}
}

// WithPayload adds the payload to the update chart not found response
func (o *UpdateChartNotFound) WithPayload(payload *models.APIResponse) *UpdateChartNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update chart not found response
func (o *UpdateChartNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateChartNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateChartInternalServerErrorCode is the HTTP code returned for type UpdateChartInternalServerError
const UpdateChartInternalServerErrorCode int = 500

/*UpdateChartInternalServerError Internal Server Error

swagger:response updateChartInternalServerError
*/
type UpdateChartInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewUpdateChartInternalServerError creates UpdateChartInternalServerError with default headers values
func NewUpdateChartInternalServerError() *UpdateChartInternalServerError {
	return &UpdateChartInternalServerError{}
}

// WithPayload adds the payload to the update chart internal server error response
func (o *UpdateChartInternalServerError) WithPayload(payload *models.APIResponse) *UpdateChartInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update chart internal server error response
func (o *UpdateChartInternalServerError) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateChartInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
